version: '3.8'

services:
    sqldb:
        container_name: sqldb
        image: "mcr.microsoft.com/mssql/server"
        ports:
            - 1434:1433
        environment:
            SA_PASSWORD: "Jobsity11"
            ACCEPT_EULA: "Y"
        volumes: 
            - sqldb:/var/opt/mssql
    zookeeper:
        image: confluentinc/cp-zookeeper:7.0.1
        hostname: zookeeper
        container_name: zookeeper
        ports:
          - "2181:2181"
        environment:
          - ZOOKEEPER_CLIENT_PORT=2181
          - ZOOKEEPER_TICK_TIME=2000
    kafka:
        image: confluentinc/cp-kafka:7.0.1
        hostname: kafka
        container_name: kafka
        depends_on:
          - zookeeper
        ports:
          - "9092:9092"
          #- "9101:9101"
        environment:
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_BROKERID=1
            - ALLOW_PLAINTEXT_LISTENER="yes"
            - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092
            - KAFKA_LISTENERS=PLAINTEXT://:29092,PLAINTEXT_HOST://:9092
            - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
            - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1